@startuml
'skinparam linetype ortho
left to right direction
package Endpoints {
    package Command {
        class "run" as Run <<(H,lightgreen)>>
    }
    package Http {
        class "GET /" as Get <<(H,lightgreen)>>
    }
}

package domain {
    package useCases {
        class Poll <<U,pink>>
        class GetRunLog <<U,pink>>
    }

    package Entities {
        class Event <<(D, yellow)>>
    }
}

package Presenters {

    package EventBusOut {
        class "axis.<topic>.[success|fail]" as EventPub <<(E,lightblue)>>
    }

    package HTTPResponse {

        class httpGet <<(B, lightblue)>>
    }
}

Run --> domain.useCases.Poll
domain.useCases.Poll --> Presenters.EventBusOut.EventPub
Endpoints.Http.Get --> domain.useCases.GetRunLog
domain.useCases.GetRunLog --> Presenters.HTTPResponse.httpGet

package DataProviders {
    class Repo <<D, lightgreen>>
}

package DB {
    class event_queue <<(T, lightblue)>>
    class run_log <<(T, lightblue)>>
    class StoredProcedures <<(P, lightblue>>
    StoredProcedures -u-> event_queue
}
DB <--> DataProviders
DataProviders <-u-> domain.useCases
@enduml