@startuml
left to right direction
package "Data Flow" {
    class "caller" as Caller1 {
        This caller will receive data
        from the called component
    }
    class "caller" as Caller2 {
        This caller will NOT receive data
        from the called component
    }
    class "component" as Return1
    class "component" as Return2
    Return1 <-u-* Caller1
    Caller2 --> Return2
}

package "Color Coding" {
    package "Domain Layer" {
        class UseCase <<U,pink>>
        class Entity <<D, yellow>>
    }
    package "Adapter Layer" {
        class Database <<D, lightgreen>>
        class Handler <<H, lightgreen>>
        class "Event Bus" <<E, lightgreen>>
    }
    package "Driver Layer" {
        class "TCP Request" <<B, lightblue>>
        class "Database Table" <<T, lightblue>>
        class "External Service" <<S, lightblue>>
    }
    "Domain Layer" -[hidden]->"Adapter Layer"
}


@enduml