@startuml
title Inventory rebuild only for relevanty regions (simple library)
Prebuild -> GetInventory: InventoryID(1)
GetInventory -> GetInventory: where inventoryID = 1
GetInventory -> Prebuild: ID: 1,\nlibraryID: 2,\nregions: [1],\ntitle: 1,\n...etc...
Rebuild -> GetProduct: productID (1)
GetProduct -> Rebuild: title1
Rebuild -> GetInventory: productID (1), regionIDs (1)
GetInventory -> GetInventory: where product = 1 and region = 1
GetInventory -> Rebuild: inventory[region1]
Rebuild -> Rebuild: doc1[title1 + region1 inventory]
Rebuild -> Region1: doc1

newpage
title Inventory rebuild only for relevanty regions (multi-region library)
Prebuild -> GetInventory: InventoryID(1)
GetInventory -> GetInventory: where inventoryID = 1
GetInventory -> Prebuild: ID: 1,\nlibraryID: 2,\nregions: [1,2],\ntitle: 1,\n...etc...
Rebuild -> GetProduct: productID (1)
GetProduct -> Rebuild: title1
Rebuild -> GetInventory: productID (1), regionIDs (1,2)
GetInventory -> GetInventory: where product = 1 and region = 1
GetInventory -> GetInventory: where product = 1 and region = 2
GetInventory -> Rebuild: inventory[[region1],[region2]]
Rebuild -> Rebuild: doc1[title1 + region1 inventory]
Rebuild -> Rebuild: doc2[title1 + region2 inventory]
Rebuild -> Region1: doc1
Rebuild -> Region2: doc2
@enduml