@startuml

user -> searchservice: search + libraryID 1
searchservice -> inventoryaccessservice: libraryID 1
inventoryaccessservice -> searchservice: inventoryIDs 1,2,3
searchservice -> cogsearch: inventoryid in 1,2,3 AND NOT (inventoryid = 1 and available = -1)
cogsearch -> searchservice: titles 1,2,3
searchservice -> inventoryservice: libraryID 1, productIDs 1,2,3
inventoryservice -> inventoryaccessservice: libraryID 1
inventoryaccessservice -> inventoryservice: inventoryIDs 1,2,3; productIDs 1,2,3
inventoryservice -> searchservice: productID: 1, inventoryID: 1, avail: true\nproductID: 2, inventoryID: 1, avail: false\nproductID: 3, inventoryID: 2, avail: true
searchservice -> searchservice: plug inventory data into title data

searchservice -> user: results



@enduml
