@startuml
left to right direction
skinparam linetype ortho
!define AzurePuml dist
!include AzurePuml/AzureCommon.puml
!include AzurePuml/Databases/AzureCosmosDb.puml
!include AzurePuml/Compute/AzureAppService.puml
!include AzurePuml/Containers/AzureKubernetesService.puml
!include AzurePuml/Containers/AzureContainerApp.puml
!include AzurePuml/Databases/AzureSqlServer.puml
!include AzurePuml/Analytics/AzureEventHub.puml
!include AzurePuml/AIMachineLearning/AzureCognitiveServices.puml

AzureEventHub(dataEventHub, "Event Stream", "200,000,000 operations per month")

rectangle current {
    AzureAppService(vendorAPI, "Vendor API","as is",)
    AzureAppService(boundless, "Boundless","as is",)
}
AzureKubernetesService(k8s, "K8s","3 D2 v3 (2 vCPUs, 8 GB RAM)",) {
    AzureContainerApp(axisPoller, "Axis Poller","pod",)
    AzureContainerApp(inventoryService, "Inventory Service","pod",)
    AzureContainerApp(titleService, "Title Service","pod",)
    AzureContainerApp(searchETL, "Search ETL","pod",)
    AzureContainerApp(searchService, "Search Service","pod",)
}

AzureSqlServer(SQL, "SQL Server","as is",) {
    database "titleService" as titleSQL
    database "inventoryService" as inventorySQL
    database "LIUD" as axisSQL
}
AzureCosmosDb(searchGather,"search gathering"," 7,000 RU/s x 730 Hours, 900 GB",)
AzureCognitiveServices(CogSearch,"CogSearch","Storage Optimized L1",)

k8s -> searchGather
searchGather -> "CogSearch"
dataEventHub <--> k8s
current -> dataEventHub
SQL -> k8s
SQL -> current
current -> "CogSearch"
@enduml